# Generated by Django 5.0.4 on 2024-09-12 21:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bid_alter_listening_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listening',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='listingWatchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
